### ISSUE TITLE
Can share the codes about Sampling and ensembling?

### ISSUE THREAD

**Issue by shipengai** [Sense-X/TSD#1]
Thanks for your work!  
Can share the code about CAS(Class-Aware Sampling) ,Adj-Nms and Ensembling models ?
Thanks.

**Comment by shipengai** [comment]
The plan to share ‘SENet’ backbone?

**Comment by shipengai** [comment]
The code about truncated loss?

**Comment by songguanglu** [comment]
Hi, 
    We have the plan to reimplement the 'SENet' based on this project.
    The methods about the OpenImage will also be released in the future.

**Comment by feifei-Liu** [comment]
Can share the code of cascade rcnn?

**Comment by songguanglu** [comment]
> Can share the code of cascade rcnn?

Hi, It needs further code modification to cooperate with Cascade RCNN. We will add supports for Cascade RCNN and Mask RCNN in the next update.
