### ISSUE TITLE
Could you share the time cost of train and test, comparing to without TSD?

### ISSUE THREAD

**Issue by lint39** [Sense-X/TSD#13]
Hi, thanks for your excellent job!!
Could you share the time cost of train and test, comparing to without using TSD?
It is important for us who don't have strong GPUs.

**Comment by songguanglu** [comment]
Hi，for standard Faster RCNN with R50, the training time is 0.55s per batch (Batchsize=2, V100 GPU) and for TSD, the training time is about 0.62s per batch. At the inference stage, TSD will bring external 10% time and the sibling head is deprecated.
