### ISSUE TITLE
About the confidence threshold

### ISSUE THREAD

**Issue by wangerxiao001** [Sense-X/TSD#18]
Hello, I have a question for you. It's about the confidence threshold. I see that the confidence threshold to visualize the bboxes and masks is 0.3 as follows:
`# TODO: merge this method with the one in BaseDetector
def show_result(img,
                result,
                class_names,
                score_thr=0.3,
                wait_time=0,
                show=True,
                out_file=None):
    """Visualize the detection results on the image.

    Args:
        img (str or np.ndarray): Image filename or loaded image.
        result (tuple[list] or list): The detection result, can be either
            (bbox, segm) or just bbox.
        class_names (list[str] or tuple[str]): A list of class names.
        score_thr (float): The threshold to visualize the bboxes and masks.
        wait_time (int): Value of waitKey param.
        show (bool, optional): Whether to show the image with opencv or not.
        out_file (str, optional): If specified, the visualization result will
            be written to the out file instead of shown in a window.`

but during the evaluation ti is 0.00.

`test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.00, nms=dict(type='nms', iou_thr=0.5), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)`

But the confidence threshold in some other model is different, so I want to ask was that any rules about the confidence threshold? Or we can just set annually by ourself?

**Comment by songguanglu** [comment]
If you want to compare with other methods fairly, you should use the same threshold. If you want to obtain a high performance in detection challenge, you can directly set it to 0.

**Comment by wangerxiao001** [comment]
> If you want to compare with other methods fairly, you should use the same threshold. If you want to obtain a high performance in detection challenge, you can directly set it to 0.
OK! Thanks for your attention!
