### ISSUE TITLE
Question about how to set finest_scale value?

### ISSUE THREAD

**Issue by wangjue-wzq** [Sense-X/TSD#21]
[finest_scale](https://github.com/Sense-X/TSD/blob/144fc96eed9a27b8caf61ab36ff31920a8522efe/mmdet/models/bbox_heads/tsd_bbox_head.py#L219)

I noticed that before the feature extractor in the TSD branch, features are mapped to four levels according to their size. But the finest_scale is set to 56*[2, 4, 8], its size is very different from the anchor point size 8 * [4, 8, 16, 32, 64]. It may cause rois_ and delta_c and delta_r to be at the same level according to their rois_ size, but the feature x2 used to calculate delta_c and delta_r comes from other feature levels. Will this cause differences in features?

**Comment by songguanglu** [comment]
Hi, we make the finest_scale consistent with the original configuration in mmdet. The finest_scale in [TSD](https://github.com/Sense-X/TSD/blob/144fc96eed9a27b8caf61ab36ff31920a8522efe/mmdet/models/bbox_heads/tsd_bbox_head.py#L219) should be the same as it in [sibling head](https://github.com/Sense-X/TSD/blob/master/mmdet/models/roi_extractors/single_level.py#L29). 
Here we have fixed the value in a less flexible way (If your algorithm requires to change it in sibling head, you should also change it to the same value in [TSD](https://github.com/Sense-X/TSD/blob/144fc96eed9a27b8caf61ab36ff31920a8522efe/mmdet/models/bbox_heads/tsd_bbox_head.py#L219)). The finest_scale means the scale threshold which is used to control the RoI scales mapping to level 0.

**Comment by wangjue-wzq** [comment]
Thanks for your reply, I have solved this problem.
