### ISSUE TITLE
How to illustrate the heatmap thermal diagram?

### ISSUE THREAD

**Issue by Derek-Kun** [Sense-X/TSD#27]
I've read the paper "Revisiting the Sibling Head in Object Detector". In this paper, a sensitive heat map of sensitivity for Location and Classification has been illustratied to show the problem of  spatial misalignment. However, this paper doesn't show how to get the sensitivity number at different location.  Is there anyone can tell me the specific method of getting sensitivity at each location? 
Thks.

**Comment by songguanglu** [comment]
[https://github.com/Sense-X/TSD/issues/25](url)

**Comment by songguanglu** [comment]
#25
