### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by dereyly** [Sense-X/TSD#3]
In paper you have multi loss
L=Lrpn+Lcls+Lloc +LDcls+LDloc+Mcls+Mloc
Is this same quality as standard mmdetection losses or results is better with Margin Loss and your special IoU loss?
Or this losses inside TSDSharedFCBBoxHead?

PS: thank you publishing this code, especial at mmdetection i love it

**Comment by songguanglu** [comment]
Hi, the losses Lrpn, Lcls, Lloc, LDcls and LDloc are same as the standard mmdetection losses. Mcls and Mloc can help further performance improvement and it's computed in the function bbox_target_single_tsd in 'core/bbox/bbox_target.py'.
