### ISSUE TITLE
rcnn nms score_thre？

### ISSUE THREAD

**Issue by luuuyi** [Sense-X/TSD#5]
Hello, I notice that rcnn header's nms score_thre in TSD is 0.00, which in normal setting is 0.05. In TSD paper, I haven't notice some chapter to declare this. Is this a fair comparsion?

**Comment by songguanglu** [comment]
Hi，we evaluate the performance under the same score_thresh for the comparison between TSD and base model. The score_thresh will slightly affect the performance of ~0.2. You can use the normal setting for research and use 0.00 for the challenge.

**Comment by luuuyi** [comment]
@songguanglu OK, I will try
