### ISSUE TITLE
The x101_64x4d model of train and inference is very very slow?

### ISSUE THREAD

**Issue by lexiqi** [Sense-X/TSD#6]
when i train faster_rcnn_x101_64x4d_fpn_TSD.py, the train and inference is very slow. The inference speed is just 0.8 task/s。 (the others model is normal)

**Comment by songguanglu** [comment]
Hi, limited by the GPU memory, the checkpoint mechanism is used when training faster_rcnn_x101_64x4d_fpn_TSD.py, and the multi-scale test will slow down the inference speed.
You can set the with_cp=False with imgs_per_gpu=1 to perform training.

**Comment by lexiqi** [comment]
ok，get√，thank you!!

**Comment by jiangyangzhou** [comment]
Hello, I tese it on 1 V100, and the inference speed is only 0.2 task/s, is it a normal  phenomenon ?  Thanks.

**Comment by jiangyangzhou** [comment]
Hello, I test faster_rcnn_x101_64x4d_fpn_TSD.py  on 1 V100, and the inference speed is only 0.2 task/s, is it a normal phenomenon ? Thanks.
