### ISSUE TITLE
Can TSDSharedFCBBoxHead work fine in Cascade?

### ISSUE THREAD

**Issue by luuuyi** [Sense-X/TSD#7]
Hello, have you ever test TSDSharedFCBBoxHead in Cascade RCNN? If so, shall we replace SharedFCBBoxHead with TSDSharedFCBBoxHead normally?

**Comment by songguanglu** [comment]
Hi, we only test TSD with Cascade RCNN in OpenImage and for COCO dataset, we don't combine them for evaluation. It needs further code modification to cooperate with Cascade RCNN. We will add supports for Cascade RCNN and Mask RCNN in the next update.

**Comment by kalayan** [comment]
We look forward to use TSD in Cascade RCNN.

**Comment by sunpeng1996** [comment]
Hi, @songguanglu , May I ask you when you add supports for Cascade RCNN and Mask RCNN?  Thanks!

**Comment by songguanglu** [comment]
> Hi, @songguanglu , May I ask you when you add supports for Cascade RCNN and Mask RCNN? Thanks!

Hi, the corresponding codes for Cascade RCNN and Mask RCNN have been done and we are performing experiments with the variant backbones to evaluate the performance. The code and pre-trained models will be released next week (ETA <=6.10).

**Comment by lint39** [comment]
Waiting for update! @songguanglu

**Comment by panjianning** [comment]
Waiting for update! @songguanglu

**Comment by sunpeng1996** [comment]
Waiting for update!
