### ISSUE TITLE
i can train your model(ap 49.2)successfully on my own datasets,but it doesn't output eval info per epoch

### ISSUE THREAD

**Issue by kiddliao** [Sense-X/TSD#9]
it's my eval setting
![image](https://user-images.githubusercontent.com/57079702/82749789-2b1f6600-9dde-11ea-83f2-23dd7039025b.png)
your implementation is the best models in mmdetection which i can get,other good models in mmdetection need mask label,
but your model performs not good on my own datasets with pafpn

**Comment by kiddliao** [comment]
![image](https://user-images.githubusercontent.com/57079702/82749871-c7e20380-9dde-11ea-9a10-f9362cb1d80c.png)

**Comment by songguanglu** [comment]
Hi, the eval info per epoch should be given if you correctly give the configuration and you can also evaluate the performance through the offline manner. 

The first thing to determine is whether the base model is appropriate for your training set. If your dataset is completely different from COCO, the default configuration of anchor maybe not appropriate for your training set.
If the base model can perform a satisfactory performance on your own dataset, TSD can steadily further improve performance.
If there still exists the problem for TSD, you can provide more experimental details.

**Comment by fengepsilon** [comment]
./tools/dist_train.sh  configs/faster_rcnn_x101_64x4d_fpn_TSD.py  8 --validate
